@PORT = 5000
@BASEURL = http://localhost:{{PORT}}

@PREFIX = api/v1
@URL = {{BASEURL}}/{{PREFIX}}

###
GET {{BASEURL}}/health
###
POST {{URL}}/auth/signup
Content-Type: application/json

{
    "fullName": "Kabir",
    "email": "kabir@gmail.com",
    "password":"Admin@123",
    "bio":"A backend dev",
    "twitter":"twitter.com",
    "facebook":"facebook.com"
    
}
###
POST {{URL}}/auth/signin
Content-Type: application/json

{
    "email": "kabir@gmail.com",
    "password":"Admin@123"
}

###
POST {{URL}}/article/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwiaWF0IjoxNzkxMjg0ODAwLCJleHAiOjE3OTEyOTIwMDB9.s0xcmVPmTsbA01Qz4hZS4AKiAXsWqpWmMJ-TiOvE1yc
Content-Type: application/json

{
    "title":"A short story",
    "text":"This is a story of two woodcutters, who lived in a village and earned their livelihood by chopping off the trees and selling them everyday.",
    "description": "WoodCutter's Story"
}

###
POST {{URL}}/media/presigned-url/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwiaWF0IjoxNzkxMjg0ODAwLCJleHAiOjE3OTEyOTIwMDB9.s0xcmVPmTsbA01Qz4hZS4AKiAXsWqpWmMJ-TiOvE1yc

{
    "contentType": "image/jpeg",
    "size":123
}
###
POST {{URL}}/media/presigned-url/article
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwiaWF0IjoxNzkxMjg0ODAwLCJleHAiOjE3OTEyOTIwMDB9.s0xcmVPmTsbA01Qz4hZS4AKiAXsWqpWmMJ-TiOvE1yc

{
    "contentType": "image/jpeg",
    "size":123,
    "articleId": "1",
    "position":0
}

###
GET {{URL}}/media/2/confirm
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwiaWF0IjoxNzkwODMyMDU3LCJleHAiOjE3OTA4MzkyNTd9.qiY_2h-fXenA2OotB7clHkFzpJYkEMI6XD_d5mUhknM