@PORT = 5000
@BASEURL = http://localhost:{{PORT}}

@PREFIX = api/v1
@URL = {{BASEURL}}/{{PREFIX}}

###
GET {{BASEURL}}/health
###
POST {{URL}}/user/signup
Content-Type: application/json

{
    "fullName": "Kabir",
    "email": "kabir@gmail.com",
    "password":"Admin@123",
    "bio":"A backend dev",
    "twitter":"twitter.com",
    "facebook":"facebook.com"
    
}
###
POST {{URL}}/user/signin
Content-Type: application/json

{
    "email": "namra@gmail.com",
    "password":"Admn@123"
}