@PORT = 5000
@BASEURL = http://localhost:{{PORT}}

@PREFIX = api/v1
@URL = {{BASEURL}}/{{PREFIX}}

###
GET {{BASEURL}}/health
###
POST {{URL}}/user/signup
Content-Type: application/json

{
    "fullName": "Kabir",
    "email": "kabir@gmail.com",
    "password":"Adm3"
}
###
POST {{URL}}/user/signin
Content-Type: application/json

{
    "email": "kabir@gmail.com",
    "password":"Admin@123"
}