/**
 * This file was generated by kysely-generate.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type MediaStatus = "active" | "deleted" | "pending";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Article {
  author: Int8;
  createdAt: Generated<Timestamp>;
  description: string;
  id: Generated<Int8>;
  text: string;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface ArticleTag {
  articleId: Int8;
  createdAt: Generated<Timestamp>;
  tagId: Int8;
  updatedAt: Generated<Timestamp>;
}

export interface Comment {
  articleId: Int8;
  author: Int8;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<Int8>;
  text: string;
  updatedAt: Generated<Timestamp>;
}

export interface Media {
  articleId: Int8 | null;
  commentId: Int8 | null;
  createdAt: Generated<Timestamp>;
  fileSize: number;
  id: Generated<Int8>;
  key: string;
  mimeType: string;
  status: Generated<MediaStatus>;
  updatedAt: Generated<Timestamp>;
  userId: Int8;
}

export interface Social {
  createdAt: Generated<Timestamp>;
  facebook: string | null;
  linkedin: string | null;
  twitter: string | null;
  updatedAt: Generated<Timestamp>;
  userId: Int8;
}

export interface Tag {
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface User {
  bio: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  fullName: string;
  hash: string;
  id: Generated<Int8>;
  imageId: Int8 | null;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  article: Article;
  articleTag: ArticleTag;
  comment: Comment;
  media: Media;
  social: Social;
  tag: Tag;
  user: User;
}
